#!/usr/bin/env bash
# Installing nginx web server
sudo apt-get update
sudo apt-get install -y nginx
sudo service nginx start
echo 'server {
    listen 80;
    server_name _;
    root /var/www/html;
    index index.html;

    location / {
        default_type text/plain;
        return 200 "Hello World!\n";
    }
}' > /etc/nginx/sites-available/default
sudo service nginx reload
