#!/usr/bin/env bash
# Installing nginx web server
sudo apt-get update
sudo apt-get install -y nginx
sudo service nginx start
sudo ufw allow 'Nginx HTTP'
sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -R 755 /var/www
cp /var/www/html/index.nginx-debian.html /var/www/html/index.nginx-debian.html.bckp
echo -e "Hello World!" > /var/www/html/index.nginx-debian.html
sudo sed -i '11i\   rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/def
echo "Ceci n'est pas une page" >> /var/www/html/error_404.html
sudo sed -i '12i\   error_page 404 /error_404.html;' /etc/nginx/sites-available/def
sudo service nginx restart
