#!/usr/bin/env bash
# Install and configure HAproxy
sudo apt-get -y update
sudo apt-get -y install haproxy
echo "
frontend eyerusalem_frontend
        bind *:80
        mode http
        default_backend eyerusalem_backend
backend eyerusalem_backend
        balance roundrobin
        server 524003-web-01 18.206.232.35:80 check
        server 524003-web-02 54.85.25.20:80 check" >> /etc/haproxy/haproxy.cfg

sudo service haproxy restart
